### ISSUE TITLE
multiline strings always start with \n or do not strip

### ISSUE THREAD

**Issue by Profpatsch** [dhall-lang/Haskell-Dhall-Library#126]
```
''
  foo
  bar
''
```

gives `"\nfoo\nbar\n"`.

That does not correspond to the nix interpretation, which results in `"foo\nbar\n"`.

If one wants to avoid the starting newline, one loses stripping:

```
  ''foo
    bar
''
```

results in `"foo\n    bar\n"` (same with nix).

Since one can always insert a prefixing `\n`, I suppose we align our multiline strings with nix.

**Comment by Gabriel439** [comment]
See #128 and let me know if that satisfies your needs
